### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by vinkla** [Art4/json-api-client#2]
Is there any documentation anywhere?

**Comment by Art4** [comment]
Not at the moment. I'm first working on fitting the spec. (#1)

In principle you can access all data through `get*()` or `get('*')` methods as shown in the [README Usage section](https://github.com/Art4/json-api-client#usage).

```php
echo $document->getMeta()->getInfo();
```

I'm planning to implement a better way like `echo $document->meta->info` but this needs more thoughts.

**Comment by vinkla** [comment]
Okay, I'll watch the repository for updates. Thanks for sharing.

**Comment by Art4** [comment]
FYI: Documentation (first drafts) is here: [docs/](https://github.com/Art4/json-api-client/blob/master/docs/README.md)

**Comment by vinkla** [comment]
:+1:
