### ISSUE TITLE
How to validate pagination link in relationship objects?

### ISSUE THREAD

**Issue by Art4** [Art4/json-api-client#21]
@fcastillo-es commented [6. Nov. 2015 10:57 MEZ](https://github.com/Art4/json-api-client/pull/20#issuecomment-154367577):
> There's one thing in the json-api documentation I don't feel totally ok with. It states that pagination likns MUST appear in the link objects that correspond to a collection. The only way to validate that it's a collection is checking if data is an array, but a relationship MUST contain at least one of links, data and meta. So if there can be a relationship with no data, we can't validate that the pagination refers to a collection.
> 
> I'm not sure in this case if it wold be worth it check if there is data to validate it as array to allow pagination. What do you think?

**Comment by Art4** [comment]
From spec [about relationships](http://jsonapi.org/format/1.0/#document-resource-object-relationships):
> A "relationship object" **MUST** contain at least one of the following:
> - `links`: ...
> - `data`: ...
> - `meta`: ...
>
> A relationship object that represents a to-many relationship **MAY** also contain pagination links under the `links` member, as described below.

and [about pagination](http://jsonapi.org/format/1.0/#fetching-pagination):
> To paginate an included collection returned in a compound document, supply pagination links in the corresponding links object.

So, if I understand you correct your question is: How to validate the pagination links in the following situation?

```
{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "links": {
      "self": "http://example.com/articles/1"
    },
    "relationships": {
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments",
          "first": "http://example.com/articles/1/comments?page=1",
          "last": "http://example.com/articles/1/comments?page=10",
          "prev": "http://example.com/articles/1/comments?page=1",
          "next": "http://example.com/articles/1/comments?page=2"
        }
       // Notice: No 'data' attribute
      }
    }
  }]
}
```

The pagination links should only present if a data attribute with an array inside exists. So the example can't be valid JSON API. It has to have either no pagination links or have a data attribute with an array inside.

But JsonApiClient validates it as correct. So I think this is a bug in the library and should be fixed.

**Comment by fcastillo-es** [comment]
Yes, I agree with your conclusion.

**Comment by Art4** [comment]
So, how should this be fixed? I think, the pagination links should just be ignored if no data attribute exists.

Another solution would be throwing an exception if pagination links exists without data, but I prefer the first solution.

**Comment by fcastillo-es** [comment]
According to this issue https://github.com/json-api/json-api/issues/736, if there is no data property there is no way to determine if the relationship is to-one or to-many, so I think the client should apply the validation only in case data is present. If there is no data, the issue includes a real world example in which pagination is needed, so I would not validate.

If a next version of the spec adds a way to know this, then the client could be updated.

**Comment by Art4** [comment]
Thanks. I'm now working on a fix.
