### ISSUE TITLE
Error parsing relationship links

### ISSUE THREAD

**Issue by fcastillo-es** [Art4/json-api-client#22]
Given this sample code:

```php
$jsonapi = '{
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {
      "comments": {
        "links": {
          "custom": "http://example.com/articles/1/custom",
          "self": "http://example.com/articles/1/relationships/comments",
          "related": {
            "href": "http://example.com/articles/1/comments",
            "meta": {
              "count": 10
            }
          },
          "first": "http://example.com/articles/1/comments?page=1",
          "last": "http://example.com/articles/1/comments?page=10",
          "prev": "http://example.com/articles/1/comments?page=1",
          "next": "http://example.com/articles/1/comments?page=2"
        }
      }
    }
  }]
}';


$manager = new \Art4\JsonApiClient\Utils\Manager();
$document = $manager->parse($jsonapi);

print_r($document->asArray(true));
```

The *related* link produces:

```
Uncaught exception 'Art4\JsonApiClient\Exception\ValidationException' with message 'property "related" has to be a string, "object" given.'
```

Even thought the spec states that a link MUST be represented as either a [string or a link object](http://jsonapi.org/format/#document-links). Also note the *related* link is taken directly from an example in the spec so it should be valid.

Also, if I remove the *related* link, the string validates but the client discards the *custom* link. The spec states in the [Relationship section](http://jsonapi.org/format/#document-resource-object-relationships) that a links object contains at least one of self and related. [Links sections](http://jsonapi.org/format/#document-links) doesn't add limitations to the contents of the links member more than the representation as a string or link object, so I conclude I should be able to add any link with any name I choose.

**Comment by Art4** [comment]
Thank you for reporting this issue. I'm trying to clearing out which `Link` objects are affected with this bug. Also I've just found the jsonapi schema. They [published it](https://github.com/json-api/json-api/commit/401d55536ea4636ecf2116c20a79a791bbb1775b) just one day after my first commit https://github.com/Art4/json-api-client/commit/0f1c6862fdbb1d1f32c5eddc5b93374bdd4073ef. This could have saved me a lot of headache. :sweat_smile: 

This objects exists:

### DocumentLink

- `related` attribute can be object: :x:
- Allows custom properties: :x:

### ErrorLink

- `related` attribute can be object: :x:
- Allows custom properties: :x:

### Link

- `related` attribute can be object: :white_check_mark:
- Allows custom properties: :white_check_mark:

### RelationshipLink

- `related` attribute can be object: :x:
- Allows custom properties: :x:

**Comment by geoffroycochard** [comment]
Hie,

Sorry to reopen this one, but i've got the same error on relationship.
Excepted this specification relationship links could be an object like https://jsonapi.org/format/1.0/#document-links and so respect this schema

```json
    "relationships": {
      "vid": {
        "data": {
          "type": "taxonomy_vocabulary--taxonomy_vocabulary",
          "id": "e0b18172-b9fa-4a2f-88c0-ed19dca65a1b"
        },
        "links": {
          "self": {
            "href": "*/jsonapi/taxonomy_term/district/3fa7e3cd-ce96-4be7-abac-7203bf8a9f4f/relationships/vid"
          },
          "related": {
            "href": "*/jsonapi/taxonomy_term/district/3fa7e3cd-ce96-4be7-abac-7203bf8a9f4f/vid"
          }
        }
      },
```

**Comment by Art4** [comment]
@geoffroycochard Thank you for the comment. I can confirm this as a bug. Could you please create a new issue for this?
