### ISSUE TITLE
id should not be mandatory in Resource\Item

### ISSUE THREAD

**Issue by danielebriggi** [Art4/json-api-client#24]
As specified here http://jsonapi.org/format/#crud-creating

> A resource can be created by sending a POST request to a URL that represents a collection of resources. The request MUST include a single resource object as primary data. The resource object MUST contain at least a type member.

the resource object can be specified without _id_ in case of POST request.

Without _id_ (but with type and attributes specified) validator fails:
https://github.com/Art4/json-api-client/blob/master/src/Resource/Item.php row:46

Am I misunderstanding the json api specifications?

**Comment by danielebriggi** [comment]
My fault, I'm sorry, I misunderstood the purpose of this library. 
I use it for parsing requests in json api format but, as written in the readme

> JsonApiClient is a PHP Library to validate and handle the response body **from** a JSON API Server.

Thus the *id* must be mandatory as it already is.

**Comment by Art4** [comment]
This is not possible at the moment but is on the goals list for release 1.0:

> Handle/validate a client request body

I leave this issue open if someone has the same issue.

Contributions are welcome. :smile:
