### ISSUE TITLE
Why is Document final?

### ISSUE THREAD

**Issue by stadskle** [Art4/json-api-client#25]
I am testing this client and wanted to extend the document as suggested in the documentation using the factory. I only wanted to add functionality, not change any of the existing methods so instead of implementing the interface I wanted to extend the existing Document class. 

As this is set as final, that is impossible. Why is that? For just wanting to add functionality that makes a lot more sense than forcing me to implement the get/has etc. methods all over again?

**Comment by Art4** [comment]
See #18.

**Comment by stadskle** [comment]
Thanks, that works!

**Comment by stadskle** [comment]
One more thing (sorry if I am misusing this thread for questions, just let me know). 

When getting a 
Art4\JsonApiClient\Resource\Collection

**Comment by Art4** [comment]
> One more thing (sorry if I am misusing this thread for questions, just let me know). 

No problem.

I think your question is incomplete. :wink:

**Comment by stadskle** [comment]
My bad, was not suppose to post it... Thanks.
