### ISSUE TITLE
IdentifierCollectionInterface should extend CollectionInterface

### ISSUE THREAD

**Issue by OskarD** [Art4/json-api-client#32]
I am building an extension to this library and to see if a resource's data contains an item or collection, I have to do this:

 `is_a($resource, IdentifierCollectionInterface::class) || is_a($resource, CollectionInterface::class);
`

They both extend `AccessInterface`, so this should have no affect on functionality

**Comment by OskarD** [comment]
It seems I had an outdated version that had CollectionInterface instead of the more recently added ElementInterface, but the result should be the same

**Comment by Art4** [comment]
The `data` attribute in the root `Document` cannot contain an `IdentifierCollectionInterface`. This would harm the JSON API spec. A collection in `Document` can only contain a `CollectionInterface`, so you have to check only `is_a($resource, CollectionInterface::class);`

See the docs for possible values in `Document`: https://github.com/Art4/json-api-client/blob/master/docs/objects-document.md#properties

**Comment by OskarD** [comment]
I understand. Thank you :)

**Comment by Art4** [comment]
You're welcome. :blush:
