### ISSUE TITLE
Is it possible to validate error objects?

### ISSUE THREAD

**Issue by TroodoNmike** [Art4/json-api-client#35]
I wonder if there is a way to use library so that it validates error objects?

Based on: http://jsonapi.org/examples/#error-objects

**Comment by Art4** [comment]
Sure, see this test: https://github.com/Art4/json-api-client/blob/master/tests/integration/ErrorParsingTest.php

**Comment by TroodoNmike** [comment]
Thanks art,

Now I see there is more stuff in the library. Didnt notice the export-ignore in .gitattributes. Is this common practice?

Cheers

**Comment by Art4** [comment]
This is a good practice to keep the download for production environments small. In most cases you don't need the tests and docs in production. If you want these files, you can clone the repository.

You can read more about this practice here: https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production

**Comment by TroodoNmike** [comment]
👍
