### ISSUE TITLE
Creating a resource without id can't be parsed

### ISSUE THREAD

**Issue by vdhicts** [Art4/json-api-client#39]
See: http://jsonapi.org/format/#crud-creating which contains the following example:

```
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```
The JsonApiClient\Utils\Helper::isValid will fail on this because of line 76 of ResourceItem.php, which requires a resource id:

```
if ( ! property_exists($object, 'id') )
{
    throw new ValidationException('A resource object MUST contain an id');
}
```

This check might be unnecessary.

**Comment by Art4** [comment]
Thank you for this issue. `Helper::isValid()` works only with a response body atm. I will add a new `Helper::isValidRequestBody()` method for this use case.

**Comment by vdhicts** [comment]
Nice solution!

**Comment by Art4** [comment]
Release 0.9 is out now.
