### ISSUE TITLE
Parser::isValidResponseString(...) bug

### ISSUE THREAD

**Issue by hackerboydotcom** [Art4/json-api-client#55]
Considering this JSON string:
```json
{
   "data":{
      "type":"fulfillments",
      "attributes":{
         "x":[]
      },
      "id":"6d7e759b-5eab-4b3f-87d1-6d098411f2b8",
      "relationships":{
         "x":{
            "data":[
               
            ]
         }
      }
   }
}
```
When trying to verify this with Parser::isValidResponseString(), it returns `false` but it MUST returns `true` instead.
"attributes" and "relationships" don't share the same namespace.
I understand that you might have a mistake for this spec from JSONAPI.org website:

"However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use."

It means we CANNOT have an attribute member "relationships" or "links", it DOESN'T mean they share the same namespace.

**Comment by Art4** [comment]
Hey there and thank you for your issue.

You have cited the [Attributes section](https://jsonapi.org/format/1.0/#document-resource-object-attributes) and you are right about attributes. But please see the [Fields section](https://jsonapi.org/format/1.0/#document-resource-object-fields) above: (highlights by me)

> ### Fields
> 
> A resource object’s attributes and its relationships are collectively called its “fields”.
> 
> Fields for a resource object MUST share a common namespace with each other and with type and id. In other words, **a resource can not have an attribute and relationship with the same name, nor can it have an attribute or relationship named type or id**.

So in my understanding one cannot use `x` in attributes AND relationships.

I hope this will help you.

**Comment by Art4** [comment]
I'd take a deeper look and I'm now sure that this is not a bug. 

As you can see in the json-api git repository there was an alternative description of the now final version:

> The members of the attributes object ("attributes") share a namespace with the
> members of the relationships object of the resource object; that is, attributes
> of a given resource object **MUST** be named differently than its relationships.
> The attributes object **MUST NOT** contain `id` or `type` members.

Source: https://github.com/json-api/json-api/pull/705/files

But the most important point I've found here: https://discuss.jsonapi.org/t/why-cant-resource-object-attributes-contain-id-type-or-any-foreign-keys/337/3

If your example would be valid than we would have a problem with referencing of “fields” in query parameters like `include` or `sort`.

```
GET /fulfillments?sort=x
```

You would have to prefix the parameters to make this clear like this:

```
GET /fulfillments?sort=attributes.x
GET /fulfillments?sort=relationships.x
```

But thanks to the shared namespace of the attributes members and relationships members we can keep it simple.

**Comment by hackerboydotcom** [comment]
Thank you for the detailed explanation, I was checking around with some special cases and found this one, I tried to validate this case with this tool (https://jsonapi-validator.herokuapp.com/) and it shows valid result and obviously that tool was wrong.
I've checked all the reference you sent above and agreed that they do share the same namespace.
Gonna close this issue.
